# Generated by Django 5.2 on 2025-04-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaCombate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida', models.IntegerField(default=100)),
                ('mana', models.IntegerField(default=50)),
                ('atributos', models.JSONField(default=dict)),
                ('barras_personalizaveis', models.JSONField(default=dict)),
                ('dados', models.JSONField(default=dict)),
                ('anotacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
