# Generated by Django 5.2 on 2025-04-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combate', '0001_initial'),
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichacombate',
            name='ficha_base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combate', to='fichas.ficha'),
        ),
    ]
