# Generated by Django 5.2 on 2025-04-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('D&D 5e', 'Dungeons & Dragons 5ª Edição'), ('Vampiro', 'Vampiro: A Máscara'), ('Cthulhu', 'Chamado de Cthulhu')], max_length=100)),
                ('nome_personagem', models.CharField(max_length=100)),
                ('raça', models.CharField(blank=True, max_length=50, null=True)),
                ('classe', models.CharField(blank=True, max_length=50, null=True)),
                ('nível', models.IntegerField(default=1)),
                ('atributos', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ficha_combate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='combate.fichacombate')),
            ],
        ),
    ]
